<a href="https://colab.research.google.com/github/starlton/Deep-Learning/blob/main/week1_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Open a fresh Jupyter notebook. Title it week1_day1.ipynbcode
2. Create 3 vectors with np.array. Compute all pairwise dot products using ONLY np.dot — no loops, yet


In [ ]:
import numpy as np

v1 = np.array([[1, 2],
               [3, 4]])
v2 = np.array([[2, 3],
               [4, 5]])
v3 = np.array([[3, 4],
               [5, 6]])

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[3, 4],
              [5, 0]])
np.dot(A,B)

array([[13,  4],
       [29, 12]])

3. Write matrix_multiply(A, B) from scratch using only loops and indexing — no np.dot, no @exercise


In [ ]:
# EXAMPLE A & B
# A = [[1, 2], [3, 4]]

# np.array([[1, 2],
#           [3, 4]])
# B = [[3, 4], [5, 6]]

def matrix_multiply(A, B):
  rows_A = len(A)
  cols_A = len(A[0])
  rows_B = len(B)
  cols_B = len(B[0])

  if cols_A != rows_B:
    return "Dimensions not equal, can't compute matrix multiplication"

  # Initialize result matrix with zeros

  result = [[0] * cols_B for _ in range(rows_A)]


  for i in range(rows_A):
    for j in range(rows_B):
      for k in range(cols_A):
        result[i][j] += A[i][k] * B[k][j]

  return np.array(result)

matrix_multiply(A,B)



array([[13,  4],
       [29, 12]])

4. Benchmark your version vs np.dot on a 100×100 matrix — print the speedup factorcode


In [ ]:
import timeit

# 2. Setup the 100x100 test data
size = 100
# Use float64 for fair comparison with NumPy
A = np.random.rand(size, size).tolist()
B = np.random.rand(size, size).tolist()
A_np = np.array(A)
B_np = np.array(B)

# 3. Benchmark your function
# Using lambda to pass arguments to timeit
timer_custom = timeit.Timer(lambda: matrix_multiply(A, B))
custom_time = timer_custom.timeit(number=10) # Run 10 times

# 4. Benchmark np.dot
timer_numpy = timeit.Timer(lambda: np.dot(A_np, B_np))
numpy_time = timer_numpy.timeit(number=10)

# 5. Calculate and print results
speedup = custom_time / numpy_time

print(f"Custom function time: {custom_time:.4f} seconds")
print(f"np.dot time: {numpy_time:.4f} seconds")
print(f"Speedup factor: {speedup:.2f}x")

Custom function time: 0.8779 seconds
np.dot time: 0.0041 seconds
Speedup factor: 211.66x


5. Implement softmax(x) from scratch without looking it up — test it on [1, 2, 3, 4], verify outputs sum to 1.0exercise


In [ ]:
from scipy.special import softmax
nums = [1, 2, 3, 4]
softmax(nums)

array([0.0320586 , 0.08714432, 0.23688282, 0.64391426])

What softmax does in one sentence: it takes a list of any numbers and squashes them into probabilities — all positive, all summing to 1.
Why ML needs it: imagine a neural network outputs raw scores for 4 classes: [1, 2, 3, 4]. Those aren't probabilities — they don't sum to 1, and they could be negative. Softmax converts them into a proper probability distribution so you can say "the model is 64% confident it's class 4."
The formula, broken into plain English:
For each number x_i in your list:

Raise e to the power of x_i → this makes everything positive
Divide by the sum of all those exponentials → this makes everything sum to 1

So for input [1, 2, 3, 4], you'd compute:
e^1, e^2, e^3, e^4        ← step 1: exponentiate everything
sum those four numbers     ← step 2: get the total
divide each one by total   ← step 3: normalize
Now try to code it — you only need import numpy as np and two lines of logic. Don't look anything up. The steps above map almost directly to NumPy operations you already used today.
One hint on structure: your function takes an array x and returns an array of the same length. What NumPy function raises e to a power? If you're not sure, try np. and tab-complete, or just think about what "exponential" is called in math libraries.
What does your first attempt look like?
      

In [ ]:
def my_softmax(nums):
  e_list = []
  for x_i in nums:
    e_list.append(np.exp(x_i))

  sum_E = sum(e_list)

  return_arr = []

  for x_i in e_list:
    return_arr.append(x_i/sum_E)



  return np.array(return_arr)



print(softmax(nums))
print("\n")
my_softmax(nums)



[0.0320586  0.08714432 0.23688282 0.64391426]




array([0.0320586 , 0.08714432, 0.23688282, 0.64391426])

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[3, 4],
              [5, 6]])

A@B

array([[13, 16],
       [29, 36]])

In [ ]:
np.dot(A,B)

array([[13, 16],
       [29, 36]])

6. Add a markdown cell explaining in your own words: why does matrix shape (m,n)@(n,p) give (m,p)?
