<a href="https://colab.research.google.com/github/starlton/Deep-Learning/blob/main/week1_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. New notebook week1_day2.ipynb. Implement cosine_similarity(a, b) in one vectorized line — no loops. Test: ([1,0],[0,1]) → 0, ([1,1],[1,1]) → 1, ([1,0],[-1,0]) → -1.exercise



In [ ]:
import numpy as np

def cosine_similarity(A,B):
  dot_product = np.dot(A,B)

  enormA = np.linalg.norm(A)
  enormB = np.linalg.norm(B)

  result = dot_product/(enormA*enormB)

  return result

v1 = [1,1]
v2 = [1, 1]

cosine_similarity(v1, v2)





np.float64(0.9999999999999998)

2. Broadcasting: given matrix X of shape (100,3), subtract the column means in one line — no loops. Confirm X.shape is still (100,3) after.exercise


In [ ]:
X = np.random.rand(100,3)
#X = np.zeros((100,3))
#X.shape
#X[0].shape

# compute column means — hint: np.mean has an axis parameter
# what axis gives you one mean per column?
means = np.mean(X, axis=0)  ### Axis =1 will result in error

# axis = 0 goes through rows down (Vertical)
# axis = 1 goes through columns across (Horizontal)

# subtract in one line — no loops
X_centered = X - means

print(X[0])
print(X_centered.shape)  # should be (100, 3)
print(means)
print(X_centered[0])

[0.59345471 0.27626202 0.73013579]
(100, 3)
[0.40789656 0.55885453 0.52130558]
[ 0.18555815 -0.28259251  0.20883021]



3. Implement normalize_rows(X) — divide each row by its L2 norm so every row has length 1. No loops. Verify every row norm equals 1.0 using np.linalg.norm.exercise


In [ ]:
def normalize_rows(X):
  l2_norm = np.linalg.norm(X, axis=1, keepdims=True)
  result = X / l2_norm

  print(X.shape)
  print(result.shape)

  return result

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])



result = normalize_rows(A)

np.linalg.norm(result, axis=1)  # Summing up all rows
#print(result) <- Uncomment this line to see full matrix

(3, 3)
(3, 3)


array([1., 1., 1.])

4. Markdown cell: explain broadcasting in your own words — what rule does numpy follow when shapes don't match exactly?code