<a href="https://colab.research.google.com/github/starlton/Deep-Learning/blob/main/week1_day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

def linear_layer(X, W, b):
  """
  Implements a Linear Layer: Y = X @ W.t + b
  """

  # Linear Transformation
  Y = np.dot(X, W.T) + b

  print(f"Input shape: {X.shape} -> Weight.T shape: {W.T.shape} -> Output shape: {Y.shape}")

  return Y



In [9]:
# 1. Initialize data and parameters
# Shape: (Batch Size=2, Input Features=4)
X = np.random.randn(2, 4)

# Layer 1: 4 input -> 3 hidden units
W1 = np.random.randn(3, 4)
b1 = np.random.randn(3)

# Layer 2: 3 hidden -> 2 output units
W2 = np.random.randn(2, 3)
b2 = np.random.randn(2)

# Layer 3: For fun

#W3 = np.random.randn(1, 2)
#b3 = np.random.randn(1)

print(f"Input X shape: {X.shape}\n")

# 2. Chain the layers
print("Forward Pass - Layer 1:")
hidden = linear_layer(X, W1, b1)

print("\nForward Pass - Layer 2:")
output = linear_layer(hidden, W2, b2)

# Last for fun trial
#print("\nForward Pass - Layer 3:")
#new = linear_layer(output, W3, b3)



print(f"\nFinal Output shape: {output.shape}")
#print(f"\nFinal Modified Output shape: {new.shape}")

Input X shape: (2, 4)

Forward Pass - Layer 1:
Input shape: (2, 4) -> Weight.T shape: (4, 3) -> Output shape: (2, 3)

Forward Pass - Layer 2:
Input shape: (2, 3) -> Weight.T shape: (3, 2) -> Output shape: (2, 2)

Final Output shape: (2, 2)


Warmup: Implement softmax from scratch again! (Good practice)

In [22]:
import numpy as np

def my_softmax(X):
  e_list = []

  for x_i in X:
    e_list.append(np.exp(x_i))

  sum_E = sum(e_list)

  result = []

  for x_i in e_list:
    result.append(x_i/sum_E)

  return np.array(result)

print(my_softmax([1,2,3,4]))


[0.0320586  0.08714432 0.23688282 0.64391426]


1. NumPy: np.linalg.inv, np.linalg.det — what do they return?


In [23]:
A = np.array([[1, 2],
              [3, 4]])

detA = np.linalg.det(A) # ad - bc -> 4-6 -> -2
detA

np.float64(-2.0000000000000004)

np.linalg.det returns the Determinant of a given matrix. The determinant represents the scaled volume (or area in 2D) of a shape after the matrix transformation is applied.

In [29]:
inverseA = np.linalg.inv(A)
"""
A^-1 =

1/det(A) * [[d, -b],
            [-c, a]]
"""

inverseA

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

np.linalg.inv returns the Inverse of a given matrix. If an original matrix rotates, scales, or skews a set of points, applying the inverse matrix returns those points back to their exact original positions.

2. Verify: A @ inverseA = identity

In [34]:
A@inverseA

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])