<a href="https://colab.research.google.com/github/starlton/Deep-Learning/blob/main/week1_day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 1. New notebook week2_pca.ipynb. Create a random (100×3) matrix X. Mean-center it using your broadcasting code from Week 1. Print mean of each column after — must be ~0. #


In [13]:
import numpy as np
np.random.seed(123)
X = np.random.rand(100, 3)
X[:5, :] # First 5 rows

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426]])

In [26]:
means = np.mean(X, axis=0)
X_centered = X - means

print("Mean Centered X shape:")
print(X_centered.shape)


X_centered_means = np.mean(X_centered, axis=0)
# don't use np.round() to see full numbers
print(f"Mean of each column: {np.round(X_centered_means)}")

# Verification
print("Verification (all close to 0):", np.allclose(X_centered_means, 0))

Mean Centered X shape:
(100, 3)
Mean of each column: [0. 0. 0.]
Verification (all close to 0): True



# 2. Compute the covariance matrix: cov = np.cov(X_centered.T). Print its shape — must be (3×3). Print the matrix. What do the diagonal values tell you?exercise
Verify the covariance matrix is symmetric: np.allclose(cov, cov.T) must return True. #


In [31]:
cov = np.cov(X_centered.T)

print("Covariance Matrix Shape:", cov.shape)

cov


Covariance Matrix Shape: (3, 3)


array([[ 0.08008798, -0.00521733, -0.00595456],
       [-0.00521733,  0.07192032,  0.00212749],
       [-0.00595456,  0.00212749,  0.08859387]])

In [33]:
np.allclose(cov, cov.T) # Verification that Covariance Matrix is symmetric

True

### The diagonal values of a covariance matrix represent the variance of each individual variable. They measure how much each variable spreads out from its mean, with higher values indicating greater spread. ###

In [36]:
variances = np.diag(cov)

print("Diagonal Values (Variances):")
print(f"Variable 1: {variances[0]:.6f}")
print(f"Variable 2: {variances[1]:.6f}")
print(f"Variable 3: {variances[2]:.6F}")

Diagonal Values (Variances):
Variable 1: 0.080088
Variable 2: 0.071920
Variable 3: 0.088594


# 3. Now try on a dataset with clear structure: make two correlated features — x = np.random.randn(100); y = 2*x + np.random.randn(100)*0.3. Stack into X, compute cov matrix. What do the off-diagonal values look like vs uncorrelated data? #


In [43]:
np.random.seed(24) # Best Number

x = np.random.randn(100)
y = 2*x + np.random.randn(100)*0.3

X = np.stack((x,y))


X_cov = np.cov(X)

X_cov

array([[1.08093686, 2.20479546],
       [2.20479546, 4.57526628]])

### Using NumPy to generate and analyze the correlated data, the off-diagonal values in the covariance matrix become significantly positive and large, whereas uncorrelated data would show values close to zero. ###

# 4. Markdown cell: explain in your own words — what does the covariance matrix tell you about your data that the mean doesn't? #

### Feature Comparison: Mean Vector vs. Covariance Matrix ($\Sigma$)

| Feature | Mean Vector ($\mu$) | Covariance Matrix ($\Sigma$) |
| :--- | :--- | :--- |
| **Information** | Center of mass/gravity | Shape, spread, & orientation |
| **Components** | Average of each variable | Variances (diag) & Covariances (off-diag) |
| **Answers** | "Where is the data?" | "How are the variables related?" |
| **Visualization**| A single point | An ellipse or ellipsoid |