<a href="https://colab.research.google.com/github/starlton/Deep-Learning/blob/main/Week%205/week5_pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [15]:
a = torch.tensor([1, 2])
b = torch.tensor([3, 4])

a @ b

tensor(11)

In [24]:
c = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
c = torch.from_numpy(c)

c.shape, c.dtype, c

(torch.Size([2, 4]),
 torch.int64,
 tensor([[1, 2, 3, 4],
         [5, 6, 7, 8]]))

In [35]:
d = c
e =d
e.numpy()

e[0][0] = 1500

d, e

(tensor([[1500,    2,    3,    4],
         [   5,    6,    7,    8]]),
 tensor([[1500,    2,    3,    4],
         [   5,    6,    7,    8]]))

2. Recreate your micrograd example in torch: a=tensor(2., requires_grad=True) etc, f=(a+b)*c, call f.backward(). Confirm a.grad, b.grad, c.grad match what micrograd gave (4, 4, 5).exercise


In [73]:
a = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)
c = torch.tensor(4., requires_grad=True)

d = a + b
d.retain_grad()

f = d * c

print(f.item())

f.backward()

a.grad, b.grad, c.grad, d.grad

20.0


(tensor(4.), tensor(4.), tensor(5.), tensor(4.))

3. Verify a gradient by hand: build a small expression, call backward, check the .grad against your own derivative. Feel that .backward() = your hand-written backward pass.exercise


In [16]:
a = torch.tensor(-4., requires_grad=True)
b = torch.tensor(2., requires_grad=True)
c = a + b ; c.retain_grad()
d = a * b + b**3 ; d.retain_grad()
c += c + 1
c += 1 + c + (-a)
d += d * 2 + (b + a).relu()
d += 3 * d + (b - a).relu()
e = c - d ; e.retain_grad()
f = e**2
f.retain_grad()
g = f / 2.0 ; g.retain_grad()
g += 10.0 / f
print(f'{g.data:.4f}') # prints 24.7041, the outcome of this forward pass
g.backward()

a.grad, b.grad, c.grad, d.grad, e.grad, f.grad, g.grad

24.7041


(tensor(138.8338),
 tensor(645.5773),
 tensor(-6.9417),
 tensor(6.9417),
 tensor(-6.9417),
 tensor(0.4958),
 tensor(1.))

4. Rebuild a single Dense layer with nn.Linear(784, 128). Inspect its .weight and .bias — note PyTorch made the parameters for you, with init built in.code


In [26]:
import torch.nn as nn

layer = nn.Linear(784, 128)

layer, layer.weight.shape, layer.bias.shape

(Linear(in_features=784, out_features=128, bias=True),
 torch.Size([128, 784]),
 torch.Size([128]))

5. Build a tiny 2-layer net with nn.Sequential(nn.Linear, nn.ReLU, nn.Linear). Notice: this is exactly your MLP's layer list — same idea, framework version.exercise

In [27]:
in_features = 5
hidden = 10
outs = 2

model = nn.Sequential(
    nn.Linear(in_features, hidden),
    nn.ReLU(),
    nn.Linear(hidden, outs)
)

model

Sequential(
  (0): Linear(in_features=5, out_features=10, bias=True)
  (1): ReLU()
  (2): Linear(in_features=10, out_features=2, bias=True)
)