<a href="https://colab.research.google.com/github/starlton/Deep-Learning/blob/main/week1_day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
A = np.array([[2, 1],
              [1, 2]])

evals, evecs = np.linalg.eig(A)

print(evals)
print(evecs)

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


### 3. Verify Av = λv for each eigenpair ###

In [11]:
for i in range(len(evals)):
    lambda_ = evals[i]
    vector = evecs[:, i]

    # Calculate Av
    Av = A @ vector
    # Calculate λv
    lambdav = lambda_ * vector

    # Check if Av ≈ λv
    is_close = np.allclose(Av, lambdav)

    print(f"Eigenpair {i+1}: {'Passed' if is_close else 'Failed'}")
    print(f"  Av: {Av}")
    print(f"  λv: {lambdav}")

# 4. Verify all pairs at once (efficient way)
# A @ v matches w * v column-wise due to broadcasting
is_all_correct = np.allclose(A @ evecs, evecs * evals)
print(f"\nAll eigenpairs verified: {is_all_correct}")

Eigenpair 1: Passed
  Av: [2.12132034 2.12132034]
  λv: [2.12132034 2.12132034]
Eigenpair 2: Passed
  Av: [-0.70710678  0.70710678]
  λv: [-0.70710678  0.70710678]

All eigenpairs verified: True


Try a non-symmetric matrix: [[1,2],[3,4]]. What do the eigenvalues look like? Are they real or complex? Print and observe.

In [15]:
B = np.array([[1, 2],
              [3, 4]])

evalsB, evecsB = np.linalg.eig(B)
print("B's Eigenvalues")
print(evalsB)
print("\nB's Eigenvectors")
print(evecsB)

B's Eigenvalues
[-0.37228132  5.37228132]

B's Eigenvectors
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Use np.linalg.eigh (not eig) on the symmetric matrix. Read the docs: what is the difference between eig and eigh? Why will you always use eigh for covariance matrices in PCA?

In [21]:
np.linalg.eigh(A)

EighResult(eigenvalues=array([1., 3.]), eigenvectors=array([[-0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678]]))

First, I had the question: Why use np.linalg.eigh(A) if np.linalg.eig(A) will return the "Same" result?

Takeaways:
1. Since .eigh() is designed for symmetric matrices, it is signicantly faster than .eig() (2x) because it only looks at half of the matrix.
2. Gauranteed REAL eigenvalues.

In [22]:
#np.linalg.eig(A)
np.linalg.eigh(A)

EighResult(eigenvalues=array([1., 3.]), eigenvectors=array([[-0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678]]))

I also had the question, what happens if you run .eigh() on a non-symmetric matrix for example, B = np.array([[1, 2],
                                                [3, 4]]) ?

Answer: Will return values, but not correct ones. Since it assumes the upper left diagonal mirrors the lower right, it will inaccurately solve for evals/evecs.

Question: Why will you use .eigh() for covariance matrices when running PCA?

Answer: Covariance Matrices are symmetric!

4. Generate a random (4×4) symmetric matrix: X = np.random.rand(4,4). Get its eigenvalues with eigh. Sort them descending. These sorted eigenvectors are your principal components — print the top 2.

In [67]:
# Random 4x4 Matrix
X = np.random.rand(4,4)

# Symmetric Matrix
S = X.T @ X

# Eigen values of Symmetric
evals, evecs = np.linalg.eigh(S)

#print(evals)

# Print Eigenvalues in Descending order.
sorted_indices = np.argsort(evals)[::-1]
evals_desc = evals[sorted_indices]
evecs_desc = evecs[:, sorted_indices]


print("Eigenvalues in descending order:")
print(evals_desc)

print("Top 2 Principal Components (Eigenvectors)")
print(evecs_desc[:, :2])

Eigenvalues in descending order:
[5.58404773 0.50118548 0.16243877 0.05867752]
Top 2 Principal Components (Eigenvectors)
[[-0.51993664 -0.44675727]
 [-0.57560297 -0.42666617]
 [-0.52484875  0.74755972]
 [-0.35054372  0.24396388]]


## **Key Differences between .eig() and .eigh()** ##
### `np.linalg.eig(A)`
*   **Scope:** Works on **any** square matrix.
*   **Output:** Can produce complex/imaginary numbers (may require `.real`).

### `np.linalg.eigh(A)`
*   **Scope:** Optimized specifically for **Symmetric** or **Hermitian** matrices.
*   **Performance:** $\approx$ 2x faster than `.eig()`.
*   **Output:** Guaranteed real numbers (no `.real` needed).

---

### 💡 Why it matters for PCA
*   **Symmetry:** The covariance matrix is always symmetric.
*   **Efficiency:** `eigh()` is faster and more stable.
*   **Convenience:** Results are already sorted in ascending order

